### PR TITLE
adding pqclear

### PR DESCRIPTION
**Pull request by nikhan**
needed to reset PQ

#175

### CODE REVIEW

**Comment by mikedewar** [comment]
we sure the old queue will get gc'd?

**Comment by nikhan** [comment]
i don't know. we can just remove() every time if you like that better

**Comment by nikhan** [comment]
ok. safety first. we can try the other way once we know what we are doing.

**Comment by mikedewar** [comment]
are you self-squashing?

**Comment by mikedewar** [comment]
:black_square_button: :black_large_square: :black_medium_small_square:

**Pull request merged**
