### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mikedewar**
This is a super simple approach to documentation. One file per block. Simple, clear descriptions with supporting examples as gists and links to wikipedia for maths or more complex stuff. 

to come:
* md files for everything
* a static site generator to turn md files into html for github pages

process:
* copy template.md to blockname.md
* edit blockname.md
* commit and push

### CODE REVIEW

**Comment by nikhan** [comment]
i have the feeling that our .md files should be 80 column (or 120, or whatever) wordwrapped. thoughts?

**Comment by mikedewar** [comment]
OK :skull:

**Comment by nikhan** [comment]
lgtm. squash pls

**Comment by mikedewar** [comment]
done

**Comment by nikhan** [comment]
:apple: :green_apple:

**Pull request merged**
