### PR TITLE
interface

### PR DESCRIPTION
**Pull request by mikedewar**
this splits sources up into stores and interfaces

### CODE REVIEW

**Comment by nikhan** [comment]
please squash, maybe branch first :)

**Comment by mikedewar** [comment]
if it's OK with you, I"m going to just leave this as mostly-squashed. I don't quite know what I'm doing wrong to make all those commits three commits, but it's better than nowt.

**Comment by mikedewar** [comment]
maybe i shouldn't commit each fix during the rebase?

**Comment by nikhan** [comment]
:unamused: :dart:

**Comment by nikhan** [comment]
WILL MERGE

**Pull request merged**
